---
- name: Stop and disable {{ lb_name }}.service
  systemd:
    name: "{{ lb_name }}.service"
    enabled: false
    state: stopped
  ignore_errors: yes

- name: Remove OpenShift 4 Loadbalancer SystemD service 
  file:
    path: "/etc/systemd/system/{{ lb_name }}.service"
    state: absent

- debug:
    msg: "Podman will stay in the Host, Play with it! ;-)"