---
- name: Disable and stop {{ lb_name }}.service
  systemd:
    name: "{{ lb_name }}.service"
    enabled: no
    state: stopped

- name: Collect services facts
  service_facts:
  register: services_state

- name: Check {{ lb_name }}.service
  fail:
    msg: "Load balancer service {{ lb_name }}.service is not running!!! Please check, run: systemctl status {{ lb_name }}.service"
  when:
    - services_state.ansible_facts.services[ lb_name  + '.service'].state != 'inactive'
    - services_state.ansible_facts.services[ lb_name  + '.service'].status != 'disabled'
