---
- name: Create letsencrypt DNS record at Hetzner
  community.dns.hetzner_dns_record:
    state: present
    zone: "{{ hetzner_zone }}"
    record: "{{ item.0.key }}"
    type: TXT
    ttl: 60
    value: "{{ item.1 }}"
    # Hetzner Cloud API (Hetzner Cloud Token)
    hetzner_api_token: "{{ hetzner_cloud_api_token | default(omit) }}"
    # Legacy  API (Legacy DNS Token)
    hetzner_token: "{{ hetzner_account_api_token | default(omit) }}"
  register: hetzner_record
  loop: "{{ challenge_data_dns | default({}) | dict2items | subelements('value') }}"
