---

- name: Create DNS record at DigitalOcean
  uri:
    url: "https://api.digitalocean.com/v2/domains/{{ digitalocean_zone }}/records"
    method: POST
    headers:
      Authorization: "Bearer {{ digitalocean_token }}"
    body_format: json
    body:
      name: "{{ item.0.key | replace(public_domain, '') | regex_replace('\\.$', '') }}"
      type: TXT
      data: "{{ item.1 }}"
    status_code: 201
  register: digitalocean_records
  loop: "{{ challenge_data_dns | default({}) | dict2items | subelements('value') }}"
