apiVersion: tekton.dev/v1alpha1
kind: Pipeline
metadata:
  name: centos-8
spec:
  resources:
  - name: workspace
    type: git
  tasks:
    - name: centos8-installation
      taskRef:
        name: reset-hetzner-server
      resources:
        inputs:
        - name: hetzner-ocp4
          resource: workspace
      params:
        - name: cluster-yml-secret
          value: cluster-yml-centos8
    - name: init-server
      runAfter:
      - centos8-installation
      taskRef:
        name: init-server
      resources:
        inputs:
        - name: hetzner-ocp4
          resource: workspace
    - name: prepare-host
      runAfter:
      - init-server
      taskRef:
        name: prepare-host
      resources:
        inputs:
        - name: hetzner-ocp4
          resource: workspace
    - name: create-cluster
      runAfter:
      - prepare-host
      taskRef:
        name: generic-playbook-runner
      params:
        - name: playbook
          value: 02-create-cluster.yml
        - name: playbook-args
          value: "--skip-tags letsencrypt"
        - name: cluster-yml
          value: cluster.yml
        - name: cluster-yml-secret
          value: cluster-yml-centos8
      resources:
        inputs:
        - name: hetzner-ocp4
          resource: workspace
    - name: destroy-cluster
      runAfter:
      - create-cluster
      taskRef:
        name: generic-playbook-runner
      params:
        - name: playbook
          value: 99-destroy-cluster.yml
        - name: playbook-args
          value: "--skip-tags letsencrypt"
        - name: cluster-yml
          value: cluster.yml
        - name: cluster-yml-secret
          value: cluster-yml-centos8
      resources:
        inputs:
        - name: hetzner-ocp4
          resource: workspace