---
- name: Create Cloudflare DNS records via account_api_token
  community.general.cloudflare_dns:
    zone: "{{ pd_cloudflare_zone }}"
    record: "{{ item }}.{{ pd_public_domain }}"
    # 1 is auto
    ttl: 1
    type: A
    value: "{{ pd_public_ip }}"
    account_email: "{{ cloudflare_account_email }}"
    account_api_token: "{{ cloudflare_account_api_token }}"
  with_items:
    - api
    - '*.apps'
  tags:
    - public_dns
  when:
    - (pd_public_ip is defined)
    - (pd_public_ip|length > 0)
    - cloudflare_account_email is defined
    - cloudflare_account_api_token is defined


- name: Create IPv6 Cloudflare DNS records via account_api_token
  community.general.cloudflare_dns:
    zone: "{{ pd_cloudflare_zone }}"
    record: "{{ item }}.{{ pd_public_domain }}"
    # 1 is auto
    ttl: 1
    type: AAAA
    value: "{{ pd_public_ipv6 }}"
    account_email: "{{ cloudflare_account_email }}"
    account_api_token: "{{ cloudflare_account_api_token }}"
  with_items:
    - api
    - '*.apps'
  tags:
    - public_dns
  when:
    - (pd_public_ipv6 is defined)
    - (pd_public_ipv6|length > 0)
    - cloudflare_account_email is defined
    - cloudflare_account_api_token is defined

- name: Create Cloudflare DNS records via api_token
  community.general.cloudflare_dns:
    zone: "{{ pd_cloudflare_zone }}"
    record: "{{ item }}.{{ pd_public_domain }}"
    # 1 is auto
    ttl: 1
    type: A
    value: "{{ pd_public_ip }}"
    api_token: "{{ cloudflare_api_token }}"
  with_items:
    - api
    - '*.apps'
  tags:
    - public_dns
  when:
    - (pd_public_ip is defined)
    - (pd_public_ip|length > 0)
    - cloudflare_api_token is defined

- name: Create IPv6 Cloudflare DNS records via api_token
  community.general.cloudflare_dns:
    zone: "{{ pd_cloudflare_zone }}"
    record: "{{ item }}.{{ pd_public_domain }}"
    # 1 is auto
    ttl: 1
    type: AAAA
    value: "{{ pd_public_ipv6 }}"
    api_token: "{{ cloudflare_api_token }}"
  with_items:
    - api
    - '*.apps'
  tags:
    - public_dns
  when:
    - (pd_public_ipv6 is defined)
    - (pd_public_ipv6|length > 0)
    - cloudflare_api_token is defined
