---
- name: Create DNS record at Hetzner
  community.dns.hetzner_dns_record:
    state: present
    zone: "{{ hetzner_zone }}"
    record: "{{ item }}.{{ cluster_name }}.{{ public_domain }}."
    type: A
    ttl: 120
    value: "{{ pd_public_ip }}"
    hetzner_token: "{{ hetzner_account_api_token }}"
  with_items:
    - api
    - '*.apps'
  tags:
    - public_dns
  when: (pd_public_ip is defined) and (pd_public_ip|length > 0)

- name: Create IPv6 DNS record at Hetzner
  community.dns.hetzner_dns_record:
    state: present
    zone: "{{ hetzner_zone }}"
    record: "{{ item }}.{{ cluster_name }}.{{ public_domain }}."
    type: AAAA
    ttl: 120
    value: "{{ pd_public_ipv6 }}"
    hetzner_token: "{{ hetzner_account_api_token }}"
  with_items:
    - api
    - '*.apps'
  tags:
    - public_dns
  when: (pd_public_ipv6 is defined) and (pd_public_ipv6|length > 0)
