---
- name: create cloudflare DNS records
  cloudflare_dns:
    zone: "{{ pd_cloudflare_zone }}"
    record: "{{ item }}.{{ pd_public_domain }}"
    # 1 is auto
    ttl: 1
    type: A
    value: "{{ pd_public_ip }}"
    account_email: "{{ cloudflare_account_email }}"
    account_api_token: "{{ cloudflare_account_api_token }}"
  with_items:
  - api
  - '*.apps'
  when: pd_provider == "cloudflare" 
  tags:
    - public_dns

- name: Create DNS record at Route53
  route53:
    state: present
    zone: "{{ pd_aws_zone }}"
    record: "{{ item }}.{{ pd_public_domain }}"
    type: A
    ttl: 120
    value: "{{ pd_public_ip }}"
    wait: yes
    aws_access_key: "{{ pd_aws_access_key }}"
    aws_secret_key: "{{ pd_aws_secret_key }}"
  with_items:
  - api
  - '*.apps'
  when: pd_provider == "route53"
  tags:
    - public_dns

- name: Create DNS record at GCP 
  gcp_dns_resource_record_set:
    name: "{{ item }}.{{ pd_public_domain }}." 
    managed_zone: 
        name: "{{ gcp_managed_zone_name }}"
        dnsName: "{{ gcp_managed_zone_domain }}"
    type: A
    ttl: 120
    target:
    - "{{ pd_public_ip }}" 
    project: "{{ gcp_project }}"
    auth_kind: serviceaccount
    service_account_file: "{{ gcp_serviceaccount_file }}"
    state: present
  with_items:
  - api
  - '*.apps'
  when: pd_provider == "gcp"
  tags:
    - public_dns
