- name: Create DNS record at DigitalOcean
  uri:
    url: "https://api.digitalocean.com/v2/domains/{{ digitalocean_zone }}/records"
    method: POST
    headers:
      Authorization: "Bearer {{ digitalocean_token }}"
    body_format: json
    body:
      name: "{{ item }}.{{ cluster_name }}"
      type: A
      data: "{{ pd_public_ip }}"
    status_code: 201
  with_items:
    - api
    - '*.apps'
  tags:
    - public_dns
  when: (pd_public_ip is defined) and (pd_public_ip|length > 0)


- name: Create IPv6 DNS record at DigitalOcean
  uri:
    url: "https://api.digitalocean.com/v2/domains/{{ digitalocean_zone }}/records"
    method: POST
    headers:
      Authorization: "Bearer {{ digitalocean_token }}"
    body_format: json
    body:
      name: "{{ item }}.{{ cluster_name }}"
      type: AAAA
      data: "{{ pd_public_ip }}"
    status_code: 201
  with_items:
    - api
    - '*.apps'
  tags:
    - public_dns
  when: (pd_public_ipv6 is defined) and (pd_public_ipv6|length > 0)