---
- name: Create Cloudflare DNS records
  community.general.cloudflare_dns:
    zone: "{{ pd_cloudflare_zone }}"
    record: "{{ item }}.{{ pd_public_domain }}"
    # 1 is auto
    ttl: 1
    type: A
    value: "{{ pd_public_ip }}"
    account_email: "{{ cloudflare_account_email }}"
    account_api_token: "{{ cloudflare_account_api_token }}"
  with_items:
    - api
    - '*.apps'
  tags:
    - public_dns
  when: (pd_public_ip is defined) and (pd_public_ip|length > 0)


- name: Create IPv6 Cloudflare DNS records
  community.general.cloudflare_dns:
    zone: "{{ pd_cloudflare_zone }}"
    record: "{{ item }}.{{ pd_public_domain }}"
    # 1 is auto
    ttl: 1
    type: AAAA
    value: "{{ pd_public_ipv6 }}"
    account_email: "{{ cloudflare_account_email }}"
    account_api_token: "{{ cloudflare_account_api_token }}"
  with_items:
    - api
    - '*.apps'
  tags:
    - public_dns
  when: (pd_public_ipv6 is defined) and (pd_public_ipv6|length > 0)
