---
- name: Install Azure Ansible pip dependencies
  pip:
    name:
      - packaging
      - msrest
      - msrestazure
      - azure.common
      - azure.mgmt
      - azure.storage
      - azure.mgmt.automation

- name: Create DNS record at Azure
  azure_rm_dnsrecordset:
    client_id: "{{ azure_client_id }}"
    secret: "{{ azure_secret }}"
    subscription_id: "{{ azure_subscription_id }}"
    tenant: "{{ azure_tenant }}"
    time_to_live: 120
    resource_group: "{{ azure_resource_group }}"
    relative_name: "{{ item }}.{{ cluster_name }}"
    zone_name: "{{ public_domain }}"
    record_type: A
    records:
      - entry: "{{ pd_public_ip }}"
    state: present
  with_items:
    - api
    - '*.apps'
  tags:
    - public_dns
  when: (pd_public_ip is defined) and (pd_public_ip|length > 0)

- name: Create IPv6 DNS record at Azure
  azure_rm_dnsrecordset:
    client_id: "{{ azure_client_id }}"
    secret: "{{ azure_secret }}"
    subscription_id: "{{ azure_subscription_id }}"
    tenant: "{{ azure_tenant }}"
    time_to_live: 120
    resource_group: "{{ azure_resource_group }}"
    relative_name: "{{ item }}.{{ cluster_name }}"
    zone_name: "{{ public_domain }}"
    record_type: AAAA
    records:
      - entry: "{{ pd_public_ipv6 }}"
    state: present
  with_items:
    - api
    - '*.apps'
  tags:
    - public_dns
  when: (pd_public_ipv6 is defined) and (pd_public_ipv6|length > 0)
