- name: Delete DNS record at TransIP
  uri:
    url: "https://api.transip.nl/v6/domains/{{ transip_zone }}/dns"
    method: DELETE
    headers:
      Authorization: "Bearer {{ transip_token }}"
    body_format: json
    body:
      dnsEntry:
        name: "{{ item }}.{{ cluster_name }}"
        expire: 60
        type: A
        content: "{{ pd_public_ip }}"
    status_code: 204
  with_items:
    - api
    - '*.apps'
  tags:
    - public_dns
  when: (pd_public_ip is defined) and (pd_public_ip | length > 0)

- name: Delete IPv6 DNS record at TransIP
  uri:
    url: "https://api.transip.nl/v6/domains/{{ transip_zone }}/dns"
    method: DELETE
    headers:
      Authorization: "Bearer {{ transip_token }}"
    body_format: json
    body:
      dnsEntry:
        name: "{{ item }}.{{ cluster_name }}"
        expire: 60
        type: AAAA
        content: "{{ pd_public_ipv6 }}"
    status_code: 204
  with_items:
    - api
    - '*.apps'
  tags:
    - public_dns
  when: (pd_public_ipv6 is defined) and (pd_public_ipv6|length > 0)
