---
- name: Delete DNS record at CloudFlare
  cloudflare_dns:
    state: absent
    zone: "{{ pd_cloudflare_zone }}"
    record: "{{ item }}.{{ pd_public_domain }}"
    # 1 is auto
    ttl: 1
    type: A
    value: "{{ pd_public_ip }}"
    account_email: "{{ cloudflare_account_email }}"
    account_api_token: "{{ cloudflare_account_api_token }}"
  with_items:
  - api
  - '*.apps'
  when: pd_provider == "cloudflare" 

- name: Delete DNS record at Route53
  route53:
    state: absent
    zone: "{{ pd_aws_zone }}"
    record: "{{ item }}.{{ pd_public_domain }}"
    type: A
    ttl: 120
    value: "{{ pd_public_ip }}"
    wait: yes
    aws_access_key: "{{ pd_aws_access_key }}"
    aws_secret_key: "{{ pd_aws_secret_key }}"
  with_items:
  - api
  - '*.apps'
  when: pd_provider == "route53" 

- name: Delete DNS record at GCP
  gcp_dns_resource_record_set:
    name: "{{ item }}.{{ pd_public_domain }}."
    managed_zone:
        name: "{{ gcp_managed_zone_name }}"
        dnsName: "{{ gcp_managed_zone_domain }}"
    type: A
    ttl: 120
    target:
    - "{{ pd_public_ip }}"
    project: "{{ gcp_project }}"
    auth_kind: serviceaccount
    service_account_file: "{{ gcp_serviceaccount_file }}"
    state: absent
  with_items:
  - api
  - '*.apps'
  when: pd_provider == "gcp"

- name: Delete DNS record at Azure 
  azure_rm_dnsrecordset:
    client_id: "{{ azure_client_id }}"
    secret: "{{ azure_secret }}"
    subscription_id: "{{ azure_subscription_id }}"
    tenant: "{{ azure_tenant }}"
    resource_group: "{{ azure_resource_group }}"
    relative_name: "{{ item }}.{{ cluster_name }}"
    zone_name: "{{ public_domain }}"
    record_type: A
    state: absent
  with_items:
  - api
  - '*.apps'
  when: pd_provider == "azure"
  tags:
    - public_dns
