---
- name: Include vars of stuff.yaml into the 'stuff' variable (2.2).
  ansible.builtin.include_vars: "{{ playbook_dir }}/../add-ons.yml"
  tags:
    - post-install
    - post-install-add-ons

- name: "Handle post_install_add_ons (include_role)"
  ansible.builtin.include_role:
    name: "{{ item.name }}"
    tasks_from: "{{ item.tasks_from | default('main.yml') }}"
    apply:
      tags:
        - post-install
        - post-install-add-ons
  tags:
    - post-install
    - post-install-add-ons
  with_items: "{{ post_install_add_ons | default ([]) }}"
