---

- name: Enable EPEL release
  yum:
    name:
      - epel-release.noarch
    state: present

- name: Installing KVM Packages
  yum:
    name:
      - "@virtualization-hypervisor"
      - "@virtualization-client"
      - "@virtualization-platform"
      - "@virtualization-tools"
      # ansible virt need lxml
      - python3-lxml
      - python3-pip
      # Important for python3-openshift
      - python3-requests-oauthlib
      # Need's epel - is enabled by default on hetzner
      - python3-openshift
      # It looks like firewalld is not installed in CentOS Stream
      - firewalld
    state: present

- name: Upgrade all packages
  yum:
    name: '*'
    state: latest

- name: Enable & Start firewalld
  service:
    name: firewalld
    state: started
    enabled: true

- name: Allow NFS traffic from VM's to Host
  firewalld:
    zone: libvirt
    state: enabled
    permanent: yes
    service: "{{ item }}"
  with_items:
    - nfs
    - mountd
    - rpc-bind
  notify: 'reload firewalld'

- name: Allow OpenShift traffic from VM's to Host
  firewalld:
    zone: libvirt
    state: enabled
    permanent: yes
    port: "{{ item }}"
  with_items:
    - 80/tcp
    - 443/tcp
    - 6443/tcp
    - 22623/tcp
  notify: 'reload firewalld'

- name: Allow OpenShift traffic from public to Host
  firewalld:
    zone: public
    state: enabled
    permanent: yes
    port: "{{ item }}"
  with_items:
    - 80/tcp
    - 443/tcp
    - 6443/tcp
  notify: 'reload firewalld'

- name: firewalld reload
  command: firewall-cmd --reload
