#!/usr/bin/env ansible-playbook
---
- name: Build inventory
  hosts: localhost
  connection: local
  gather_facts: no
  tasks:
  - name: Add hetzner server to inventory
    add_host: 
      name: "{{ hetzner_hostname }}"

- name: Handle RHEL Subscription
  hosts: all
  gather_facts: yes
  remote_user: root
  tasks:
  - name: RHEL Subscription
    redhat_subscription:
      state: present
      activationkey: "{{redhat_subscription_activationkey}}"
      org_id: "{{redhat_subscription_org_id}}"
      pool: "{{redhat_subscription_pool}}"
    when: ansible_distribution == "RedHat" 

  - name: Disable all RHSM repositories
    rhsm_repository:
      name: '*'
      state: disabled
    when: ansible_distribution == "RedHat" 

  - name: Enable repos for RHEL 7
    rhsm_repository:
      name:
        - rhel-7-server-rpms
        - rhel-7-server-extras-rpms
        - rhel-7-server-ansible-2.8-rpms
        - rhel-7-server-ose-4.2-rpms
        - rhel-7-server-openstack-14-rpms
      state: enabled
    when: ansible_distribution == "RedHat" and ansible_distribution_major_version == '7'

  - name: Enable repos for RHEL 8
    rhsm_repository:
      name: 
        - rhel-8-for-x86_64-baseos-rpms
        - rhel-8-for-x86_64-appstream-rpms
        - rhel-8-for-x86_64-highavailability-rpms
        - ansible-2.8-for-rhel-8-x86_64-rpms
        - openstack-15-for-rhel-8-x86_64-rpms
      state: enabled
    when: ansible_distribution == "RedHat" and ansible_distribution_major_version == '8'
    