- import_playbook: 01-prepare-host.yml
- import_playbook: 02-prepare-publicdns.yml
- import_playbook: 03-prepare-install.yml
- name: prepare and setup OCP 4
  hosts: localhost
  gather_facts: true
  vars_files:
  - ../cluster.yml
  tasks:
  - name: init Terraform
    command: terraform init
    args:
      chdir: "{{ terraform_workdir }}"
  - name: terraform plan
    command: terraform plan
    args:
      chdir: "{{ terraform_workdir }}"
  - name: terraform apply
    command: terraform apply --auto-approve
    args:
      chdir: "{{ terraform_workdir }}"
