---
  
- name: fix storage object in master ignition json
  replace:
    path: "/root/{{ cluster_name }}-install/{{item}}"
    regexp: '\"storage\":{}'
    replace: '"storage":{"filesystems":[{"mount":{"device":"/dev/vdb","format":"ext4","label":"crio"}},{"mount":{"device":"/dev/vdc","format":"ext4","label":"etcd"}}]}'
    backup: yes
  with_items:
  - "master.ign"
- name: fix systemd object in master ignition json
  replace:
    path: "/root/{{ cluster_name }}-install/master.ign"
    regexp: '\"systemd\":{}'
    replace: '"systemd":{"units":[{"name":"var-lib-containers-storage.mount","enable":true,"contents":"[Mount]\\nWhat=/dev/vdb/\\nWhere=/var/lib/containers/storage\\nType=ext4\\n[Install]\\nWantedBy=local-fs.target"},{"name":"var-lib-etcd.mount","enable":true,"contents":"[Mount]\\nWhat=/dev/vdc\\nWhere=/var/lib/etcd\\nType=ext4\\n[Install]\\nWantedBy=local-fs.target"}]}'
    backup: yes
- name: fix storage object in worker ignition json
  replace:
    path: "/root/{{ cluster_name }}-install/{{item}}"
    regexp: '\"storage\":{}'
    replace: '"storage":{"filesystems":[{"mount":{"device":"/dev/vdb","format":"ext4","label":"crio"}}]}'
    backup: yes
  with_items:
  - "worker.ign"
- name: fix systemd object in worker ignition json
  replace:
    path:  "/root/{{ cluster_name }}-install/worker.ign"
    regexp: '\"systemd\":{}'
    replace: '"systemd":{"units":[{"name":"var-lib-containers-storage.mount","enable":true,"contents":"[Mount]\\nWhat=/dev/vdb\\nWhere=/var/lib/containers/storage\\nType=ext4\\n\\n[Install]\\nWantedBy=local-fs.target"}]}'
    backup: yes
